name: forgejo

services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:${FORGEJO_VERSION:-latest}
    container_name: forgejo
    restart: unless-stopped
    environment:
      USER_UID: 1000
      USER_GID: 1000
      SSH_PORT: ${SSH_PORT}
      HTTP_PORT: ${WEB_PORT}
    volumes:
      - ${DATA_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '${WEB_PORT}:3000'
      - '${SSH_PORT}:22'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${WEB_PORT}/']
      interval: 30s
      timeout: 10s
      retries: 3
